Check if docker is running at the beginning of scripts using docker

diff --git a/scripts/build b/scripts/build
--- a/scripts/build
+++ b/scripts/build
@@ -1,4 +1,9 @@
 #!/bin/sh
 
+if ! docker info >/dev/null 2>&1; then
+    echo "ERROR: docker does not seem to be running, please run it and retry."
+    exit 1
+fi
+
 docker build -t backend .
 yes | docker image prune
diff --git a/scripts/run b/scripts/run
--- a/scripts/run
+++ b/scripts/run
@@ -1,3 +1,8 @@
 #!/bin/sh
 
+if ! docker info >/dev/null 2>&1; then
+    echo "ERROR: docker does not seem to be running, please run it and retry."
+    exit 1
+fi
+
 docker run -p 8000:8000 --rm --env-file .env backend
